import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.main}>
        <div className={styles.contents}>
          <h1 className={styles.title}>
            Victor <br /> Abiola <br /> Photographer
          </h1>
          <p className={styles.desc}>
            Event/Portrait photographer & film maker
          </p>
        </div>

        <div className="works"></div>
      </section>
    </div>
  );
};

export default Home;
