import type { NextPage } from "next";
import {GetStaticProps} from 'next'
import Head from "next/head";
import React from "react";
import { sanity } from "../sanityClient";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.main}>
        <div className={styles.contents}>
          <h1 className={styles.title}>
            Victor <br /> Abiola <br /> Photographer
          </h1>
          <p className={styles.desc}>
            Event/Portrait photographer & film maker
          </p>

          <div className={styles.arrows}>
            <div className={styles.arrow_left} role="button" aria-label="Previous Arrow button">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path
                  d="M7.828 11H20v2H7.828l5.364 5.364-1.414 1.414L4 12l7.778-7.778 1.414 1.414z"
                  fill="#fff"
                />
              </svg>
            </div>
            <div className={styles.arrow_right} role="button" aria-label="Next Arrow button">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
              >
                <path fill="none" d="M0 0h24v24H0z" />
                <path
                  d="M16.172 11l-5.364-5.364 1.414-1.414L20 12l-7.778 7.778-1.414-1.414L16.172 13H4v-2z"
                  fill="#fff"
                />
              </svg>
            </div>
          </div>
        </div>

        <div className={styles.works}>
          {posts.map((post, i) => (
            <React.Fragment key={i}>
              <div className={`slide-${i} ${styles.slide}`}>
                <img src={post.mainImage.asset.url} alt={`Work`} />
                <div className={styles.work_name}>
                  <p>{post.title}</p>
                  <p>{post.yearCreated}</p>
                </div>
              </div>
            </React.Fragment>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Home;


export const getStaticProps: GetStaticProps = async (context) => {
  const  posts  = await sanity.fetch(`*[_type == "post"]{
    'slug': slug.current,
    'title': title,
    'yearCreated': yearCreated,
    'mainImage': mainImage {
      asset->{
        _id, 
        url
      }
    }
  }`)
  console.log(posts);
  
  return {
    props: {
      posts
    }
  }
}
